### ISSUE TITLE
Fails on HTML files with other extension, e.g. *.PHP

### ISSUE THREAD

**Issue by jesper-mortensen** [middleman/middleman-minify-html#33]
Versions:

    gem 'middleman', '~>3.4.0'
    gem 'middleman-minify-html', '~> 3.4.1'

In `config.rb` the file extension is changed to PHP, like so: `set :index_file, 'index.php'`

All templates and content files named with the proper PHP extension, e.g. a content file like `index.php.md`

Expected outcome: A final file called `index.php` containing minified HTML.

Actual outcome: A final file `index.php` with un-minified HTML.

**Comment by tdreyno** [comment]
I'm sure sure you can safely compress HTML with embedded PHP.

Looks like you could set the mime-type of php files to html to get the compressor to run, but you'll want to make sure it doesn't break the code.

```
::Rack::Mime::MIME_TYPES['.php'] = 'text/html'
```
